name: ScrapeAndPush

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env: 
      DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}

    steps:
    - uses: actions/checkout@v4
    - name: Run code
      uses: actions/setup-node@v4
      with:
        node-version: 20.12.0
        cache: 'npm'
    - run: npm ci
    - run: node run.js
      
